// Module d'accès à l'API Grist : tables, colonnes, enregistrement courant
const GristAPI=(function(){let _tables=[],_columnsByTable={},_currentRecord=null,_currentMappings=null,_currentTableId=null,_currentOptions=null,_onRecordCallbacks=[];
 async function init(){grist.ready({requiredAccess:'full'});await refreshSchema();grist.onRecord((record,mappings)=>{_currentRecord=record;_currentMappings=mappings;_onRecordCallbacks.forEach(cb=>{try{Promise.resolve(cb(record)).catch(e=>console.error('[GristAPI] callback onRecord:',e));}catch(e){console.error('[GristAPI] callback onRecord:',e);}});detectCurrentContext().catch(()=>{});});grist.onOptions((options,settings)=>{_currentOptions={options,settings};detectCurrentContext().catch(()=>{});});}
 async function refreshSchema(){try{_tables=await grist.docApi.listTables();_columnsByTable={};for(const t of _tables){try{const d=await grist.docApi.fetchTable(t);_columnsByTable[t]=Object.keys(d).filter(c=>c!=='id');}catch(e){_columnsByTable[t]=[];}}}catch(e){console.error('Erreur refreshSchema',e);}}
 function getTables(){return _tables;}function getColumns(t){return _columnsByTable[t]||[];}function getAllVariables(){return _tables.flatMap(t=>getColumns(t).map(c=>({table:t,column:c,key:t+'_'+c})));}function onRecord(cb){_onRecordCallbacks.push(cb);}function getCurrentRecord(){return _currentRecord;}function getCurrentTableId(){return _currentTableId;}
 async function findReferenceColumns(from,to){try{const c=await grist.docApi.fetchTable('_grist_Tables_column'),t=await grist.docApi.fetchTable('_grist_Tables'),ids={};for(let i=0;i<t.id.length;i++)ids[t.tableId[i]]=t.id[i];const out=[];for(let i=0;i<c.id.length;i++){if(c.parentId[i]===ids[from]){const m=(c.type[i]||'').match(/^Ref(?:List)?:([^:]+)$/);if(m&&m[1]===to)out.push(c.colId[i]);}}return out;}catch(e){console.error('Erreur findReferenceColumns',e);return [];}}
 async function fetchRowById(t,id){const d=await grist.docApi.fetchTable(t),i=d.id.indexOf(id);if(i<0)return null;const r={};for(const k of Object.keys(d))r[k]=d[k][i];return r;}
 async function findRowsByReverseReference(from,to,id){const refs=await findReferenceColumns(to,from);if(!refs.length)return {refCols:[],rows:[]};const d=await grist.docApi.fetchTable(to),rows=[];for(let i=0;i<d.id.length;i++)if(refs.some(c=>{const v=d[c]&&d[c][i],a=Array.isArray(v)?v:[v];return a.some(x=>String(Array.isArray(x)?x[1]:x)===String(id));})){const r={};for(const k of Object.keys(d))r[k]=d[k][i];rows.push(r);}return {refCols:refs,rows};}
 async function detectTableId(){try{if(grist.getTable){const t=grist.getTable();if(t&&t.getTableId){const id=await t.getTableId();if(id)return id;}}}catch(e){}return _currentTableId||null;}async function detectCurrentContext(){const id=await detectTableId();if(id){_currentTableId=id;return {tableId:id,record:_currentRecord};}return null;}
 return {init,refreshSchema,getTables,getColumns,getAllVariables,onRecord,getCurrentRecord,getCurrentTableId,findReferenceColumns,fetchRowById,findRowsByReverseReference,detectTableId,detectCurrentContext};})();
