// Module de gestion des variables : autocomplétion, badges, résolution des valeurs
const Variables=(function(){
 let activeQuill=null,acBox=null,acItems=[],acSelectedIndex=0,acRange=null;
 function init(q){activeQuill=q;acBox=document.getElementById('autocomplete-box');q.on('text-change',(d,o,source)=>{if(source==='user')checkForTrigger();});q.root.addEventListener('keydown',e=>{if(!acBox||acBox.style.display!=='block')return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();moveSelection(e.key==='ArrowDown'?1:-1);}else if(e.key==='Enter'){e.preventDefault();confirmSelection();}else if(e.key==='Escape')hideAutocomplete();});document.addEventListener('click',e=>{if(acBox&&!acBox.contains(e.target))hideAutocomplete();});}
 function checkForTrigger(){const r=activeQuill.getSelection();if(!r)return hideAutocomplete();const m=activeQuill.getText(0,r.index).match(/#([A-Za-z0-9_]*)$/);if(!m)return hideAutocomplete();acRange={index:r.index-m[0].length,length:m[0].length};showAutocomplete(m[1].toLowerCase(),r);}
 function showAutocomplete(q,r){acItems=GristAPI.getAllVariables().filter(v=>v.key.toLowerCase().includes(q));if(!acItems.length)return hideAutocomplete();acSelectedIndex=0;renderAutocomplete();const b=activeQuill.getBounds(r.index),c=activeQuill.root.getBoundingClientRect();acBox.style.left=c.left+b.left+scrollX+'px';acBox.style.top=c.top+b.top+b.height+scrollY+4+'px';acBox.style.display='block';}
 function renderAutocomplete(){acBox.innerHTML='';acItems.forEach((x,i)=>{const d=document.createElement('div');d.className='ac-item'+(i===acSelectedIndex?' selected':'');d.textContent=x.key;d.addEventListener('mousedown',e=>{e.preventDefault();acSelectedIndex=i;confirmSelection();});acBox.appendChild(d);});}
 function moveSelection(d){acSelectedIndex=(acSelectedIndex+d+acItems.length)%acItems.length;renderAutocomplete();} function hideAutocomplete(){if(acBox)acBox.style.display='none';acRange=null;}
 function confirmSelection(){if(!acRange||!acItems.length)return;const x=acItems[acSelectedIndex];activeQuill.deleteText(acRange.index,acRange.length);activeQuill.insertEmbed(acRange.index,'varbadge',{table:x.table,column:x.column,key:x.key});activeQuill.setSelection(acRange.index+1,0);hideAutocomplete();}
 async function resolveVariable(varTable,varColumn,currentTableId,record){const cur=currentTableId||GristAPI.getCurrentTableId(),label=varTable+'_'+varColumn;try{if(!record)return '';if(!cur)return '[ERREUR: table courante indisponible]';if(varTable===cur)return formatValue(record[varColumn]);const refs=await GristAPI.findReferenceColumns(cur,varTable);if(refs.length){let ref=refs[0];if(refs.length>1){console.warn('[Variables][InterTable] plusieurs colonnes Ref candidates, choix multiple non résolu automatiquement, première utilisée');if(document.getElementById('ref-choice-modal'))ref=await askUserForRefColumn(refs,varTable)||refs[0];}const v=record[ref];if(!v)return '';const row=await GristAPI.fetchRowById(varTable,Array.isArray(v)?v[1]:v);return row?formatValue(row[varColumn]):'[ERREUR: ligne introuvable dans '+varTable+']';}if(record.id!=null&&GristAPI.findRowsByReverseReference){const r=await GristAPI.findRowsByReverseReference(cur,varTable,record.id);if(r.rows.length)return formatValue(r.rows[0][varColumn]);}const msg='[ERREUR: Impossible de lier '+cur+' à '+varTable+' : aucune référence trouvée entre ces tables]';console.error('[Variables][InterTable] '+msg);return msg;}catch(e){console.error('[Variables][InterTable] échec résolution '+label,e);return '[ERREUR: résolution de '+label+' impossible]';}}
 function formatValue(v){if(v==null)return '';return Array.isArray(v)?v.join(', '):String(v);} function askUserForRefColumn(rs,t){return new Promise(resolve=>{const m=document.getElementById('ref-choice-modal'),s=document.getElementById('ref-choice-select'),ok=document.getElementById('ref-choice-confirm'),cancel=document.getElementById('ref-choice-cancel');s.innerHTML='';rs.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;s.appendChild(o);});m.style.display='flex';const done=v=>{m.style.display='none';resolve(v);};ok.onclick=()=>done(s.value);cancel.onclick=()=>done(null);});}
 return {init,resolveVariable,hideAutocomplete};
})();
