@grist.UserTable
class Facture:
  NumeroFacture = grist.Text()
  DateFacture = grist.Date()
  DateEcheance = grist.Date()
  ClientNom = grist.Text()
  ClientAdresse = grist.Text()
  ClientSiret = grist.Text()
  Ligne1Designation = grist.Text()
  Ligne1Quantite = grist.Numeric()
  Ligne1PrixUnitaireHT = grist.Numeric()
  Ligne2Designation = grist.Text()
  Ligne2Quantite = grist.Numeric()
  Ligne2PrixUnitaireHT = grist.Numeric()
  Ligne3Designation = grist.Text()
  Ligne3Quantite = grist.Numeric()
  Ligne3PrixUnitaireHT = grist.Numeric()
  Ligne4Designation = grist.Text()
  Ligne4Quantite = grist.Numeric()
  Ligne4PrixUnitaireHT = grist.Numeric()
  Ligne5Designation = grist.Text()
  Ligne5Quantite = grist.Numeric()
  Ligne5PrixUnitaireHT = grist.Numeric()
  TauxTVA = grist.Numeric()
  MontantTotalHT = grist.Numeric()
  MontantTVA = grist.Numeric()
  MontantTotalTTC = grist.Numeric()
  ConditionsPaiement = grist.Text()
